version: '3'

services:
  mariadb:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clean_at_dev
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
